const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const H = require('../holiday-plans.js');
const state = () => ({ records: {}, weekends: {}, holidays: {} });
const holiday = () => ({ id: 'h', name: '测试假期', start: '2026-09-10', end: '2026-09-13', planDate: '2026-09-09' });
const draft = repeat => ({ title: '练字', subject: '语文', minutes: 10, repeat });
let s = state(), h = holiday();
H.save(s, h);
assert.deepEqual(H.find(s, '2026-09-09'), h);
h = s.holidays.h;
assert.equal(H.find(s, '2026-09-14'), undefined);
assert.equal(H.iso('2026-02-30'), false);
assert.deepEqual(H.days('2026-12-30', '2027-01-02'), ['2026-12-30','2026-12-31','2027-01-01','2027-01-02']);
assert.throws(() => H.save(s, { ...h, id: 'overlap', start: '2026-09-13', end: '2026-09-15', planDate: '2026-09-12' }), /重叠/);
assert.throws(() => H.save(s, { ...h, end: '2028-01-01' }), /366/);
H.add(s, h, { ...draft(false), title: '作文' }, [h.planDate]);
H.add(s, h, draft(true), H.days(h.start, h.end));
H.add(s, h, { ...draft(true), title: '口算', subject: '数学' }, ['2026-09-10','2026-09-12','2026-09-13']);
assert.equal(H.tasks(s, h.planDate).length, 1, 'pre-holiday date can carry one-time homework');
assert.equal(H.tasks(s, '2026-09-11').length, 1, 'repeat date exclusions do not create tasks');
assert.equal(new Set(H.refs(s).map(r => r.task.id)).size, 8, 'every occurrence has its own ID');
H.confirm(s, h);
for (const d of H.days(h.planDate, h.end)) assert(s.records[d].tasksConfirmed && s.records[d].orderSaved && s.records[d].holidayDaily);
const first = H.refs(s).find(r => r.date === h.start && r.task.title === '练字');
first.task.status = 'done'; first.task.elapsedMs = 620000; first.task.completedDate = first.date;
const originalDone = JSON.stringify(first.task);
const second = H.refs(s).find(r => r.date === '2026-09-11');
H.edit(s, second, '练字一页', 15, true, '2026-09-11');
assert.equal(JSON.stringify(first.task), originalDone, 'series edit preserves completed content and timing');
assert.equal(H.tasks(s, '2026-09-12')[0].title, '练字一页');
assert.throws(() => H.edit(s, first, '改掉已完成', 5, false, '2026-09-11'), /保留/);
H.removeTask(s, second);
assert.equal(H.tasks(s, '2026-09-11').length, 0);
assert.equal(H.tasks(s, '2026-09-12').length, 2, 'removing one repetition does not affect other days');
const dailyIds = H.tasks(s, '2026-09-12').map(t => t.id);
H.order(s, '2026-09-12', [...dailyIds].reverse());
assert.deepEqual(H.tasks(s, '2026-09-12').map(t => t.id), [...dailyIds].reverse());
assert.throws(() => H.order(s, '2026-09-12', [dailyIds[0],dailyIds[0]]), /选完/);
const late = H.refs(s).find(r => r.date === '2026-09-12' && r.task.subject === '数学');
late.task.status = 'paused'; late.task.elapsedMs = 10000; late.task.startedAt = '18:01';
H.move(s, late, '2026-09-14');
assert.equal(H.tasks(s, '2026-09-14')[0].id, late.task.id);
assert.equal(H.tasks(s, '2026-09-14')[0].elapsedMs, 10000, 'carryover keeps recorded elapsed time');
assert.equal(H.tasks(s, '2026-09-14')[0].holidayOriginalDate, '2026-09-12');
assert.equal(H.refs(s).filter(r => r.task.id === late.task.id).length, 1, 'rescheduling moves instead of cloning');
assert(s.records['2026-09-14'].tasksConfirmed, 'post-holiday carryover can be executed');
assert.throws(() => H.save(s, {...h,end:'2026-09-14'}), /保留原日期/);
assert.throws(() => H.removeHoliday(s, h.id), /不能删除/);
assert.deepEqual(JSON.parse(JSON.stringify(s)), s, 'backup round-trip keeps configuration, repetitions and status');
let conflict = state(); conflict.weekends['2026-09-11'] = { tasks: [{id:'old',title:'已有周末作业'}], confirmed: true };
const snapshot = JSON.stringify(conflict);
assert.throws(() => H.save(conflict, holiday()), /已有周末计划/);
assert.equal(JSON.stringify(conflict), snapshot, 'conflict validation never mutates existing records');
const empty = state();H.save(empty, holiday());H.confirm(empty, empty.holidays.h);H.removeHoliday(empty, 'h');
for (const record of Object.values(empty.records)) assert.equal(record.holidayDaily, undefined, 'deleting an empty confirmed holiday restores ordinary date handling');
const movedEmpty = state();H.save(movedEmpty, holiday());H.confirm(movedEmpty, movedEmpty.holidays.h);H.save(movedEmpty, {...holiday(),start:'2026-10-01',end:'2026-10-07',planDate:'2026-09-30'});
assert.equal(movedEmpty.records['2026-09-11'].holidayDaily,undefined,'changing an empty holiday clears old date markers');
const long = state(), winter={id:'winter',name:'寒假',start:'2026-12-30',end:'2027-02-01',planDate:'2026-12-29'};H.save(long,winter);H.add(long,winter,draft(true),H.days(winter.start,winter.end));
assert.equal(H.refs(long).length,34,'long holidays span months and years without duplicate days');
for (const d of H.days(winter.start,winter.end)) assert.equal(H.tasks(long,d).length,1);
const native = fs.readFileSync(path.join(__dirname, '../../android/app/src/main/java/com/homework/ledger/HolidayPlans.java'), 'utf8');
for (const field of ['holidayId','holidaySeriesId','holidayOriginalDate','holidayDaily','planDate']) assert(native.includes('"'+field+'"'), `native retains ${field} data contract`);
const html = fs.readFileSync(path.join(__dirname, '../index.html'), 'utf8');
const ui = fs.readFileSync(path.join(__dirname, '../holiday-ui.js'), 'utf8');
for (const [,id] of ui.matchAll(/\$\("#([^"\)]+)"\)/g)) assert(html.includes(`id="${id}"`), `missing holiday event binding ${id}`);
for (const [,id] of ui.matchAll(/"(holiday[A-Z][A-Za-z]+)"/g)) assert(html.includes(`id="${id}"`), `missing mapped holiday element ${id}`);
assert(html.indexOf('src="holiday-plans.js"') < html.indexOf('src="app.js"'));
console.log('PASS: holiday dates/conflicts, per-day instances, repetition exceptions, ordering, protected history, carryover, backup contract and UI bindings.');
