const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {pathToFileURL}=require('node:url');const {chromium}=require('playwright');
(async()=>{
 const output=fs.mkdtempSync(path.join(os.tmpdir(),'homework-holiday-'));
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||undefined});
 try{
  const context=await browser.newContext({locale:'zh-CN',timezoneId:'Asia/Shanghai',viewport:{width:1024,height:768}});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.clock.setFixedTime(new Date('2026-09-09T18:00:00+08:00'));
  await page.addInitScript(()=>{if(localStorage.getItem('holiday-test-seeded'))return;localStorage.setItem('holiday-test-seeded','yes');localStorage.setItem('homework-ledger-v1',JSON.stringify({records:{'2026-09-09':{ledgerConfirmed:true,ledgerAt:'17:00'}},weekends:{}}));});
  await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
  await page.locator('#settingsButton').click();await page.locator('#openHolidaySettingsButton').click();
  await page.locator('#holidayName').fill('秋日假期');await page.locator('#holidayStart').fill('2026-09-10');await page.locator('#holidayEnd').fill('2026-09-13');
  assert.equal(await page.locator('#holidayPlanDate').inputValue(),'2026-09-09');
  await page.locator('#holidayConfigForm button[type=submit]').click();
  assert.equal(await page.locator('[data-holiday-open]').count(),1);
  await page.locator('#holidaySettingsBack').click();await page.locator('#closeSettingsButton').click();
  assert.equal(await page.locator('#holidayPlanEntry').isVisible(),true);
  await page.locator('#holidayPlanEntry').click();
  assert.equal(await page.locator('#holidayViewDate').count(),0,'day navigation does not need a calendar');
  assert.deepEqual(await page.locator('#holidayShortDays strong').allTextContents(),['今天','第一天','第二天','第三天','第四天']);
  assert.equal(await page.locator('#holidayShortDays [aria-pressed=true]').getAttribute('data-holiday-view'),'2026-09-09');
  await page.locator('[data-holiday-keyword="背诵"]').click();assert.equal(await page.locator('#holidayTaskTitle').inputValue(),'背诵');
  const composerBefore=await page.locator('.holiday-input-row').boundingBox();
  await page.locator('#holidayTaskTitle').fill('书本第1页');await page.locator('#holidayTaskForm button[type=submit]').click();
  const composerAfter=await page.locator('.holiday-input-row').boundingBox();assert.equal(composerBefore.y,composerAfter.y,'adding a task keeps the composer fixed');
  assert.equal(await page.locator('#holidayTaskTitle').evaluate(e=>e===document.activeElement),true);
  await page.locator('#holidayRepeat').selectOption('daily');await page.locator('#holidayTaskTitle').fill('练字');await page.locator('#holidayTaskForm button[type=submit]').click();
  await page.locator('#holidaySubject').click();await page.locator('#holidaySubjectOptions [data-subject="数学"]').click();await page.locator('#holidayTaskTitle').fill('口算');
  await page.locator('#holidayRepeatDates summary').click();await page.locator('[data-holiday-repeat-date="2026-09-11"]').uncheck();await page.locator('#holidayRepeatDates summary').click();await page.locator('#holidayTaskForm button[type=submit]').click();
  await page.locator('[data-holiday-view="2026-09-10"]').focus();await page.keyboard.press('Space');
  assert.equal(await page.locator('[data-holiday-view="2026-09-10"]').evaluate(node=>node===document.activeElement),true,'day selection keeps keyboard focus');
  assert.match(await page.locator('#holidayDaySummary').innerText(),/2 项.*30 分钟\s*9月10日/);
  assert.equal(await page.locator('#holidayTaskMinutes').inputValue(),'15','new homework defaults to 15 minutes');
  await page.locator('#holidaySort').click();
  assert.equal(await page.locator('#holidayTaskList').getByText('选这项',{exact:true}).count(),0);
  assert.deepEqual(await page.locator('#holidayTaskList .order-number').allTextContents(),['','']);
  await page.locator('[data-holiday-estimate]').nth(0).selectOption('10');
  assert.equal(await page.locator('[data-holiday-action=pick]').nth(0).getAttribute('aria-pressed'),'false','changing estimates does not select the task');
  await page.locator('[data-holiday-action=pick]').nth(1).click();
  await page.locator('[data-holiday-view="2026-09-10"]').click();
  assert.equal(await page.locator('#holidaySort').innerText(),'确定顺序 1/2','tapping the current day preserves the sorting draft');
  await page.locator('[data-holiday-estimate]').nth(1).selectOption('20');
  assert.equal(await page.locator('[data-holiday-action=pick]').nth(1).locator('.order-number').innerText(),'1','changing estimate preserves the selected order');
  await page.locator('[data-holiday-action=pick]').nth(1).click();
  assert.equal(await page.locator('#holidaySort').innerText(),'确定顺序 1/2','repeated taps do not duplicate selections');
  await page.locator('#holidaySortReset').click();
  assert.deepEqual(await page.locator('#holidayTaskList .order-number').allTextContents(),['','']);
  await page.locator('[data-holiday-action=pick]').nth(1).locator('.task-title').click();
  assert.match(await page.locator('#holidayDaySummary').innerText(),/2 项.*30 分钟/);
  for(const width of [320,390,1024]) {
    await page.setViewportSize({width,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    for(const row of await page.locator('.holiday-order-row').all()) {
      const circle=await row.locator('.order-number').boundingBox(),title=await row.locator('.task-title').boundingBox(),estimate=await row.locator('[data-holiday-estimate]').boundingBox();
      assert.equal(circle.width,circle.height);assert(circle.x+circle.width<=title.x);assert(title.x+title.width<=estimate.x);
    }
    await page.screenshot({path:path.join(output,`holiday-sort-${width}.png`),fullPage:true});
  }
  await page.locator('[data-holiday-action=pick]').nth(0).focus();await page.keyboard.press('Space');
  assert.equal(await page.locator('[data-holiday-action=pick]').nth(0).evaluate(node=>node===document.activeElement),true,'keyboard focus remains on the selected card');
  assert.deepEqual(await page.locator('#holidayTaskList .order-number').allTextContents(),['2','1']);
  await page.locator('#holidaySort').click();
  const estimates=await page.evaluate(()=>JSON.parse(localStorage.getItem('homework-ledger-v1')).records);
  assert.deepEqual(estimates['2026-09-10'].tasks.map(t=>t.estimatedMinutes),[20,10]);
  assert(estimates['2026-09-12'].tasks.every(t=>t.estimatedMinutes===15),'changing a daily estimate does not edit other repeated instances');
  assert.match(await page.locator('#holidayTaskList .holiday-task-copy strong').first().innerText(),/口算/);
  assert.equal(await page.locator('#holidayTaskList input[type=date]').count(),0,'holiday task rescheduling uses day choices');
  assert.equal(await page.locator('#holidayTaskList [data-holiday-action=edit] svg').count(),2);
  assert.equal(await page.locator('#holidayTaskList [data-holiday-action=delete] svg').count(),2);
  for(const [width,height] of [[1024,768],[390,844],[320,740]]){
   await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
   const estimateBox=await page.locator('.holiday-entry-estimate').boundingBox(),addBox=await page.locator('#holidayTaskForm button[type=submit]').boundingBox();
   assert(estimateBox.x+estimateBox.width<=addBox.x&&Math.abs(estimateBox.y-addBox.y)<1,'estimate stays immediately left of the add button');
   await page.locator('#holidayRepeatDates summary').click();const popup=await page.locator('#holidayRepeatDateList').boundingBox();assert(popup.x>=0&&popup.x+popup.width<=width,'repeat date picker fits narrow screens');await page.locator('#holidayRepeatDates summary').click();
   await page.screenshot({path:path.join(output,`plan-${width}.png`),fullPage:true});
  }
  await page.setViewportSize({width:1024,height:460});const keyboardComposer=await page.locator('.holiday-input-row').boundingBox();assert(keyboardComposer.y+keyboardComposer.height<=460,'composer remains in the resized viewport');
  await page.setViewportSize({width:1024,height:768});await page.locator('#holidayConfirm').click();
  assert.equal(await page.locator('#startPlanModal').isVisible(),true);await page.locator('#startPlanCloseButton').click();
  assert.equal(await page.locator('#mainPage').isVisible(),true);
  assert.match(await page.locator('#taskList').innerText(),/书本第1页/);assert.doesNotMatch(await page.locator('#taskList').innerText(),/练字|口算/);
  async function date(value){await page.locator('#settingsButton').click();await page.locator('#recordDate').fill(value);await page.locator('#recordDate').dispatchEvent('change');await page.locator('#closeSettingsButton').click();}
  await date('2026-09-10');assert.equal(await page.locator('#ledgerButton').isVisible(),false);assert.match(await page.locator('#taskList').innerText(),/练字|口算/);
  await page.locator('#taskList [data-task-action=start]').click();await page.locator('#focusCompleteButton').click();
  await page.locator('#startPlanCloseButton').click();
  let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('homework-ledger-v1')));
  assert.equal(saved.records['2026-09-10'].tasks[0].status,'done');assert.equal(saved.records['2026-09-12'].tasks.find(t=>t.title==='口算').status,'pending');
  await page.locator('#holidayPlanEntry').click();await page.locator('[data-holiday-view="2026-09-12"]').click();
  const row=page.locator('#holidayTaskList .holiday-task-row').filter({hasText:'练字'});await row.locator('[data-holiday-action=edit]').click();await page.locator('#holidayEditContent').fill('练字一页');await page.locator('#holidayTaskEditForm button[type=submit]').click();
  await page.locator('#holidayConfirm').click();await date('2026-09-14');
  assert.equal(await page.locator('#holidayOverdue').isVisible(),true);await page.locator('#holidayOverdueSummary').click();
  const overdue=page.locator('#holidayOverdueList .holiday-task-row').filter({hasText:'练字一页'}).first();await overdue.locator('[data-holiday-action=move]').click();
  assert.match(await page.locator('#taskList').innerText(),/练字一页/);
  saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('homework-ledger-v1')));assert.equal(saved.records['2026-09-14'].tasks.length,1);assert.equal(Object.values(saved.holidays).length,1);
  await page.reload();assert.equal(await page.locator('#holidayPlanEntry').isVisible(),true);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('homework-ledger-v1')).holidays),saved.holidays);
  await page.evaluate(()=>localStorage.setItem('homework-ledger-v1',JSON.stringify({records:{'2026-12-29':{ledgerConfirmed:true}},weekends:{},holidays:{winter:{id:'winter',name:'寒假',start:'2026-12-30',end:'2027-02-01',planDate:'2026-12-29'}}})));
  await page.clock.setFixedTime(new Date('2026-12-29T18:00:00+08:00'));await page.reload();await page.locator('#holidayPlanEntry').click();assert.equal(await page.locator('#holidayShortDays').isVisible(),true);
  assert.equal(await page.locator('#holidayShortDays button').count(),35);
  assert.equal(await page.locator('[data-holiday-view="2026-12-30"] strong').innerText(),'第一天');
  assert.equal(await page.locator('[data-holiday-view="2027-01-01"] strong').innerText(),'第三天','day numbering continues across the year boundary');
  assert.equal(await page.locator('[data-holiday-view="2027-02-01"] strong').innerText(),'第三十四天');
  await page.locator('#holidayTaskMinutes').selectOption('10');
  await page.locator('#holidayRepeat').selectOption('daily');await page.locator('#holidayTaskTitle').fill('每天练字');await page.locator('#holidayTaskForm button[type=submit]').click();
  saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('homework-ledger-v1')));
  assert(Object.values(saved.records).flatMap(r=>r.tasks||[]).every(t=>t.estimatedMinutes===10),'every repeated instance uses the selected estimate');
  assert.equal(await page.locator('#holidayTaskMinutes').inputValue(),'10','consecutive additions retain the chosen estimate');
  await page.setViewportSize({width:320,height:740});await page.locator('[data-holiday-view="2027-02-01"]').click();assert.match(await page.locator('#holidayTaskList').innerText(),/每天练字/);
  const count=await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('homework-ledger-v1')).records).reduce((n,r)=>n+(r.tasks||[]).length,0));assert.equal(count,34);
  await page.locator('#holidayTaskMinutes').selectOption('30');
  await page.locator('#holidayRepeat').selectOption('once');await page.locator('#holidayTaskTitle').fill('假期最后一天整理书包');await page.locator('#holidayTaskTitle').press('Enter');
  saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('homework-ledger-v1')));
  assert(saved.records['2027-02-01'].tasks.some(t=>t.title==='假期最后一天整理书包'),'a one-time task is added to the day selected by its ordinal');
  assert.equal(saved.records['2027-02-01'].tasks.find(t=>t.title==='假期最后一天整理书包').estimatedMinutes,30,'keyboard submission uses the selected estimate');
  assert.equal(saved.records['2027-02-01'].tasks.find(t=>t.title==='每天练字').estimatedMinutes,10,'a new estimate leaves existing homework unchanged');
  assert.match(await page.locator('#holidayDaySummary').innerText(),/2 项.*40 分钟/);
  assert.equal(saved.records['2026-12-30'].tasks.length,1);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  let activeDay=await page.locator('#holidayShortDays [aria-pressed=true]').boundingBox();assert(activeDay.x>=0&&activeDay.x+activeDay.width<=320,'the selected day stays visible after adding a task');
  await page.screenshot({path:path.join(output,'holiday-long-days-320.png'),fullPage:true});
  await page.locator('#holidaySort').click();await page.locator('[data-holiday-action=pick]').first().click();await page.locator('[data-holiday-view="2027-01-31"]').click();
  assert.equal(await page.locator('#holidaySort').innerText(),'调整当天顺序','switching days clears only the unconfirmed sorting selection');
  assert.equal(await page.locator('#holidayTaskList .holiday-task-row').count(),1);
  await page.locator('[data-holiday-view="2027-02-01"]').click();
  const moveRow=page.locator('#holidayTaskList .holiday-task-row').filter({hasText:'假期最后一天整理书包'});
  const movingId=await moveRow.getAttribute('data-holiday-task');
  const beforeMove=await page.evaluate(()=>localStorage.getItem('homework-ledger-v1'));
  assert.equal(await moveRow.locator('[data-holiday-action=move]').count(),0,'rescheduling has no confirmation button');
  await moveRow.locator('[data-holiday-move-date]').dispatchEvent('change');
  assert.equal(await page.evaluate(()=>localStorage.getItem('homework-ledger-v1')),beforeMove,'selecting the original date does not change the saved plan');
  assert.equal(await moveRow.locator('[data-holiday-move-date] option[value="2027-01-31"]').innerText(),'第三十三天 · 1月31日');
  await page.evaluate(()=>{window.originalHolidayMove=HolidayPlans.move;HolidayPlans.move=()=>{throw new Error('所选日期已有周末计划');};});
  try {
    await moveRow.locator('[data-holiday-move-date]').selectOption('2027-01-31');
    assert.equal(await moveRow.locator('[data-holiday-move-date]').inputValue(),'2027-02-01','a rejected move restores the original day selection');
    assert.equal(await page.evaluate(()=>localStorage.getItem('homework-ledger-v1')),beforeMove,'a rejected move does not alter saved homework');
  } finally { await page.evaluate(()=>{HolidayPlans.move=window.originalHolidayMove;delete window.originalHolidayMove;}); }
  await moveRow.locator('[data-holiday-move-date]').selectOption('2027-01-31');
  assert.equal(await moveRow.count(),0,'choosing a new day immediately moves the task out of the source day');
  saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('homework-ledger-v1')));
  assert(!saved.records['2027-02-01'].tasks.some(t=>t.id===movingId));
  assert.equal(saved.records['2027-01-31'].tasks.filter(t=>t.id===movingId).length,1);
  assert.equal(saved.records['2027-01-31'].tasks.length,2,'the target day keeps its existing homework');
  assert.equal(Object.values(saved.records).flatMap(r=>r.tasks||[]).filter(t=>t.id===movingId).length,1,'rescheduling moves rather than duplicates homework');
  await page.locator('[data-holiday-view="2027-01-31"]').click();
  const movedRow=page.locator(`#holidayTaskList [data-holiday-task="${movingId}"]`);
  assert.equal(await movedRow.locator('[data-holiday-move-date]').inputValue(),'2027-01-31');
  const afterMove=await page.evaluate(()=>localStorage.getItem('homework-ledger-v1'));
  await movedRow.locator('[data-holiday-move-date]').dispatchEvent('change');
  assert.equal(await page.evaluate(()=>localStorage.getItem('homework-ledger-v1')),afterMove,'rendering the destination day and reselecting its date do not duplicate the task');
  await movedRow.getByRole('button',{name:'修改假期最后一天整理书包',exact:true}).click();
  await page.locator('#holidayEditContent').fill('整理书包和文具');await page.locator('#holidayTaskEditForm button[type=submit]').click();
  await movedRow.getByRole('button',{name:'删除整理书包和文具（仅当天）',exact:true}).click();
  assert.equal(await movedRow.count(),0,'the delete icon deletes only this task');
  assert.equal(await page.locator('#holidayTaskList .holiday-task-row').count(),1);
  await page.evaluate(()=>localStorage.setItem('homework-ledger-v1',JSON.stringify({records:{'2028-01-01':{ledgerConfirmed:true}},weekends:{},holidays:{long:{id:'long',name:'全年练习',start:'2028-01-01',end:'2028-12-31',planDate:'2028-01-01'}}})));
  await page.clock.setFixedTime(new Date('2028-04-10T18:00:00+08:00'));await page.reload();await page.locator('#holidayPlanEntry').click();
  assert.equal(await page.locator('#holidayShortDays button').count(),366,'all supported days remain reachable');
  assert.equal(await page.locator('#holidayShortDays [aria-pressed=true] strong').innerText(),'今天');
  assert.equal(await page.locator('#holidayShortDays small').count(),0,'day chips show only the day label and task count');
  assert.equal(await page.locator('#holidayDaySummary time').innerText(),'4月10日');
  assert.equal(await page.locator('#holidayDaySummary time').getAttribute('datetime'),'2028-04-10');
  assert.equal(await page.locator('[data-holiday-view="2028-01-01"] strong').innerText(),'第一天');
  assert.equal(await page.locator('[data-holiday-view="2028-04-09"] strong').innerText(),'第一百天');
  assert.equal(await page.locator('[data-holiday-view="2028-04-19"] strong').innerText(),'第一百一十天');
  assert.equal(await page.locator('[data-holiday-view="2028-12-31"] strong').innerText(),'第三百六十六天');
  activeDay=await page.locator('#holidayShortDays [aria-pressed=true]').boundingBox();assert(activeDay.x>=0&&activeDay.x+activeDay.width<=320,'opening midway through a long holiday reveals today');
  await page.screenshot({path:path.join(output,'holiday-today-320.png'),fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS: holiday settings, day navigation, leap/year boundaries, long-holiday scrolling, repeat exceptions, ordering, automatic day rescheduling and failure recovery, icon edit/delete, per-day execution, future edits, expired carryover, reload and responsive layouts.');console.log('Screenshots: '+output);await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
